### ISSUE TITLE
Upgrade Setting Error

### ISSUE THREAD

**Issue by frlhermes** [projectestac/marsupial#15]
Hi,

I installed a new version of this plugin and i got a error when "upgradesetting.php" is launched.

Call to undefined function is_marsupial_enabled() in \moodle28\local\rcommon\settings.php on line 4

I solved adding this line in "local/rcommon/settings.php":
require_once($CFG->dirroot.'/local/rcommon/locallib.php');

Regards

**Comment by crazyserver** [comment]
Hi,

Thanks for the patch! We've solved that issue right now ;)

Cheers,

Pau
