### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by Shackpack** [projectestac/marsupial#16]
Hola

Estoy intentando incorporar el presente proyecto en una instalación independiente de Moodle.
Me encuentro que la documentación existente en el proyecto de github no coincide con el contenido del paquete .zip que se descarga (marsupial_moodle_v2.6.0.5.zip) y por tanto las instrucciones de instalación no coinciden.

¿Se ha echo exclusivo para moodle agora?

Agradecería cualquier aclaración.

Saludos

**Comment by frncesc** [comment]
Hola Shackpack,

Los documentos en `docs/moodle` eran muy antiguos y correspondían a versiones de Marsupial que ya no son operativas con Moodle 2.x. Hemos aprovechado tu comentario para archivar estos documentos en la rama [historical_files](https://github.com/projectestac/marsupial/tree/historical_files) y publicar una [nueva release](https://github.com/projectestac/marsupial/releases/latest) con los cambios incorporados desde el pasado 28 de enero.

En realidad las instrucciones de instalación son muy simples: descomprimir el contenido del archivo ZIP en la raiz de la instalación de Moodle. Esto añadirá `my_books` y `rcommon` al directorio `blocks`, `rcontent` a `mod` y `rcommon` a `local`.

Ten en cuenta que la versión actual está optimizada para **Moodle 2.6**. Próximamente habrá una nueva release para Moodle 2.8.
