### ISSUE TITLE
Fallo en módulo Mis libros con Moodle 2.6.11 y marsupial 6.0.6

### ISSUE THREAD

**Issue by leticiavazquez** [projectestac/marsupial#17]
Configuramos marsupial en un moodle 2.6.11, nos aparece error al hacer las siguientes acciones y ya no podemos volver a utilizar moodle:

- si intento asociar desde el módulo de Mis libros una licencia a un usuario, una vez le doy a guardar aparece el error de las capturas (Asociar_licencia.jpg y Asociar_licencia2.jpg). si intento asociarlas a través del enlace Gestionar usuarios el error es 

- si con un usuario que tiene ya una licencia asignada, selecciono uno de los libros a través del módulo aparece el error (Mislibros.jpg)
 
![asociar_licencia](https://cloud.githubusercontent.com/assets/6682355/10074806/627efb0c-62d2-11e5-9c1b-e2ff6c399883.jpg)
![asociar_licencia2](https://cloud.githubusercontent.com/assets/6682355/10074805/627c41c8-62d2-11e5-9f2d-2ff7a36edb7f.jpg)
![mislibros](https://cloud.githubusercontent.com/assets/6682355/10074823/7e1b52ca-62d2-11e5-9dd2-b47e46405a80.jpg)

**Comment by crazyserver** [comment]
Hola Leticia,

Gracias por tus comentarios. Puedes probar con la última versión? Te la puedes descargar con el botón "Download ZIP" que encontrarás al final de la columna derecha de https://github.com/projectestac/marsupial

Coméntanos si esto resuelve tu situación.

Un saludo,

Pau

**Comment by leticiavazquez** [comment]
Buenos días, 

con la versión de moodle 2.8 y la marsupial 2.7.0.1 ya podemos trabajar correctamente con los contenidos de santillana. 

Muchas gracias, un saludo 



Leticia Vázquez Barros 




leticia.vazquez@netexlearning.com 

T. +34 981 634 067 Ext 273 


Netex 
Innovative Learning Technologies 
www.netexlearning.com 

----- Mensaje original -----

De: "Pau Ferrer Ocaña" <notifications@github.com> 
Para: "projectestac/marsupial" <marsupial@noreply.github.com> 
CC: "leticiavazquez" <leticia.vazquez@netexlearning.com> 
Enviados: Viernes, 25 de Septiembre 2015 9:34:57 
Asunto: Re: [marsupial] Fallo en módulo Mis libros con Moodle 2.6.11 y marsupial 6.0.6 (#17) 



Hola Leticia, 

Gracias por tus comentarios. Puedes probar con la última versión? Te la puedes descargar con el botón "Download ZIP" que encontrarás al final de la columna derecha de https://github.com/projectestac/marsupial 


Coméntanos si esto resuelve tu situación. 

Un saludo, 

Pau

**Comment by crazyserver** [comment]
Perfecto gracias por el aviso! :smile:
