### ISSUE TITLE
Error wsSeguimiento.lib.php

### ISSUE THREAD

**Issue by frlhermes** [projectestac/marsupial#18]
Buenas Tardes,

Hemos estado realizando sincronizaciones con el servicio de seguimiento, pero cuando intentamos realizar una sincronización con un libro que sólo tiene un registro en rcontent creado a partir del modulo "Mis Libros", da un fallo al insertar el seguimiento: "ID de módulo de curso no válida", hemos solucionado dicho problema moviendo la linea 262 " $contextmodule = context_module::instance($cm->id); " y la hemos puesto dentro del ELSE de la linea 285. El problema ocurre cuando el $rcontent->course es igual al SITEID, dando un problema en dicho proceso. Espero puedan arreglarlo. Gracias.

Un Saludo

**Comment by crazyserver** [comment]
Hola,

Muchas gracias por la notificación. Lo validaremos.

Un saludo!

**Comment by crazyserver** [comment]
https://github.com/projectestac/marsupial/commit/10ca500363d3bff9fd241b9e81b23b7c564af05f

**Comment by crazyserver** [comment]
Hemos aplicado los cambios comentados, muchas gracias! :dancer:
