### ISSUE TITLE
DTD de validación

### ISSUE THREAD

**Issue by jfbabio** [projectestac/marsupial#19]
Buenos días,

Dado que la operación ObtenerEstructura del wsBooksStructure, tiene que devolver un libro, os quería preguntar si tenéis accesible de alguna manera un DTD, XRD o XSD que pueda utilizarse para validar que el XML que se va a entregar de un libro es el correcto o no.

Un saludo y muchas gracias de antemano.

**Comment by sarjona** [comment]
Hola!

Actualmente no hay ningún DTD o esquema para validar el formato de los XML :-( Si os animáis a prepararlo y nos lo hacéis llegar, lo podemos incorporar en el código del proyecto por si alguien más lo necesita :-)

Un abrazo y hasta pronto!
