### ISSUE TITLE
Internal Server Error al abrir Gestión de Proveedores

### ISSUE THREAD

**Issue by lluchjm** [projectestac/marsupial#20]
Hola
por imposibilidad de cambiar de servidor de hosting, tenemos el siguiente entorno:

- PHP 5.3.21
- Moodle 2.6.11, actualizado desde 2.5.2
- Marsupial 2.6.0.6

Cuando accedemos al menú del Moodle...
   Administración del sitio-->
   Recursos remotos -->
   Gestionar proveedores

...nos devuelve:

   Internal Server Error
   The server encountered an internal error or misconfiguration and was unable to complete your request.

y el contenido del archivo errorlog es:

[16-Sep-2016 18:26:51 Europe/Berlin] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20090626/timezonedb.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20090626/timezonedb.so: cannot open shared object file: No such file or directory in Unknown on line 0

Gracias por cualquier ayuda

**Comment by sarjona** [comment]
El error que comentas no es debido al módulo de marsupial sinó a un problema de configuración del servidor PHP donde se encuentra vuestro espacio Moodle. Nuestra recomendación es que contactéis con vuestro proveedor de hosting y/o consultéis alguna página que explique cómo solucionarlo (por ejemplo http://stackoverflow.com/questions/12132736/unable-to-find-timezonedb-so).

Además, sería recomendable actualizar cuando podáis la versión de Moodle (y de Marsupial) ya que la 2.6 hace más de un año que no tiene soporte.
