### ISSUE TITLE
Installation on moodle 3.1, is that possible?

### ISSUE THREAD

**Issue by iuliandragomir** [projectestac/marsupial#21]
Hello, could you please tell me if marsupial supports installation on moodle 3.1? Just tried it and it throws up an error when upgrading modules/database that "Lo sentimos, el plugin "mod_rcontent" es defectuoso o no actualizado: no se puede continuar.

Debug info: Unsupported $module syntax detected in version.php
Error code: detectedbrokenplugin
Stack trace:
line 620 of /lib/upgradelib.php: plugin_defective_exception thrown
line 432 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

I have tried installing the latest marsupial version available on github (2.7.0.1)

Sorry if I posted in the wrong section and thank you for your help.

**Comment by frncesc** [comment]
Try with the new relase [v3.0.0.1](https://github.com/projectestac/marsupial/releases/tag/v3.0.0.1), just published. This version should work also with Moodle 3.1

**Comment by iuliandragomir** [comment]
Thank you, it is working just fine right now.
