### ISSUE TITLE
Descarga del catálogo de libros

### ISSUE THREAD

**Issue by lluchjm** [projectestac/marsupial#22]
Buenos dias,
tenemos instalado el Marsupial v2.7.0.1  en un Moodle 2.9.7, hospedado en un hosting compartido donde no podemos ampliar el tiempo de respuesta, etc del PHP. Por este motivo, siempre nos da error de timeout al actualizar el catálogo de una editorial.
La pregunta es la siguiente, si restauramos en local este moodle y descargamos el catálogo, bastará con restaurar en el moodle en producción (Internet) únicamente la base de datos? O también se habrán generado archivos en los directorios moodledata etc?

Gracias de antemano

**Comment by sarjona** [comment]
Hola!

En principio la información que se descarga con los servicios web de marsupial se actualiza únicamente en la base de datos. 
En algún caso puntual nos hemos encontrado problemas similares con alguna editorial porque en lugar de enviar los libros contratados por el centro envían todo el catálogo y, lo que hemos hecho para resolverlo, ha sido contactar con la editorial para pedir que revisen los servicios web para enviar sólo aquellos libros que el centro haya contratado.

Un abrazo,
Sara

**Comment by lluchjm** [comment]
Buenasss,

pues eso hemos hecho, y la editorial nos ha reducido el catálogo a  los libros que hemos contratado, aún así, siguía dando error. Después de restaurar el moodle de Internet a un ordenador local, ampliando antes el tiempo de ejecución del php, se ha descargado el catálogo completo y accede correctamente a los contenidos. El problema viene cuando volvemos a restaurar el moodle en Internet y clicamos para ver algún contenido nos muestra **en pantalla el error**:
 "Comprova l'adreça del servei web d'autenticació"

En la **tabla mdl_rcommon_errors_log** aparece el registro:
module: rcontent
action: AuthenticateUserContent_error
url: /moodle1617/mod/rcontent/view.php?id=8766
info: Error AuthenticateUserContent: Instance ID: 3535, Text: [[wsautenticationerror]], Code: -2, Detail: La credencial no és vàlida.

Incluso al clicar en **comprobar una licencia** de un usuario da fallo:
"S'ha produit un problema en intentar connectar: S'ha produït un error en llegir a la base de dades"

Se deben estos errores a alguna medida de seguridad que evita trabajar en un servidor distinto del que ha descargado el catálogo?

Muchas gracias por vuestro valioso tiempo.

**Comment by sarjona** [comment]
Hola @lluchjm !

Si habéis restaurado TODA la base de datos y en local os estaba funcionando correctamente, a priori no debería haber ningún problema (aunque nunca hemos hecho ninguna operación similar...). Nuestra recomendación es que limpies la memoria caché del Moodle y volváis a probarlo. Ahora bien, debéis tener en cuenta que, aunque os hayáis descargado la estructura de libros, si no habéis asignado ninguna credencial, los usuarios continuarán sin poder acceder. 

Un abrazo,
Sara
