### ISSUE TITLE
COMPILE_ERROR: break in local/rcommon/add_user_credential.php

### ISSUE THREAD

**Issue by sarjona** [projectestac/marsupial#25]
There is a break in the like 36 of the file local/rcommon/add_user_credential.php that would be nice to remove or replace by a return.

PHP 7.0 and higher, a break statement is no longer permitted outside a for, foreach or switch statement and gives a fatal error (https://stackoverflow.com/questions/34871198/fatal-error-break-not-in-the-loop-or-switch-context-in).

**Comment by slva** [comment]
Thanks Sara!
We change the break statement you mention due to the compatibility to php 7.X.
